trigger:
  branches:
    include:
      - main
      - segunda-etapa

pr: none

variables:
- name: NEXT_PUBLIC_MAPBOX_TOKEN
  value: 'pk.eyJ1IjoiZGlzLWNhZiIsImEiOiJjbTlkNnQ4Y2wwemt0MmtvbWQ4bHRqb3hwIn0.gGRD-8mup5EAJIMTP56xug'
- name: NEXT_PUBLIC_MAPBOX_STYLE_TOKEN
  value: 'pk.eyJ1IjoiZGlzLWNhZiIsImEiOiJjbTlkMnRiaGkwOTU5MmlvbjN3YWhobW94In0.3nz3-vM7MNId7xy7Y9q_aQ'
- name: NEXT_PUBLIC_GA_MEASUREMENT_ID
  value: "G-MWSK6BRGGX"
- name: NEXT_PUBLIC_URL
  value: "https://azapp-atlas20250922-cr.azurewebsites.net"
- name: AZURE_SERVICE_CONNECTION
  value: 'SC-WEBATLAS-CR-01'
- name: WEBAPP_NAME
  value: 'azapp-atlas20250922-cr'
- name: NODE_VERSION
  value: '20.x'
stages:
- stage: BuildAndPackage
  displayName: Build and Package Next.js App
  condition: |
    or(
      eq(variables['Build.Reason'], 'Manual'),
      contains(variables['Build.SourceVersionMessage'], '#deploy')
    )
  jobs:
  - job: Build
    displayName: Build App
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      displayName: Checkout Code
      inputs:
        repository: self
    - task: NodeTool@0
      inputs:
        versionSpec: '$(NODE_VERSION)'
      displayName: Set up Node.js
    - task: CmdLine@2
      displayName: Build with Next.js
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      env:
        NEXT_PUBLIC_MAPBOX_TOKEN: $(NEXT_PUBLIC_MAPBOX_TOKEN)
        NEXT_PUBLIC_MAPBOX_STYLE_TOKEN: $ (NEXT_PUBLIC_MAPBOX_STYLE_TOKEN)
        NEXT_PUBLIC_URL: $(NEXT_PUBLIC_URL)
      inputs:
        script: |
          npm ci
          npm run build
          cp -r .next/static .next/standalone/.next/static
          cp -r public .next/standalone/
          cp -r web.config .next/standalone/
    - task: CopyFiles@2
      inputs:
        SourceFolder: '.'
        Contents: ".next/standalone/**\n.next/static/**\npublic/**\n_del_node_modules/**\napp/**\nnode_modules/**\nnode_modules.tar.gz\noryx-manifest.toml\npackage.json\nserver.js\nweb.config          \n"
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: Copy build artifacts
    - task: ecdc45f6-832d-4ad9-b52b-ee49e94659be@1
      displayName: Publish Artifact
      inputs:
        path: $(Build.ArtifactStagingDirectory)
        artifactName: drop
- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn:
  - BuildAndPackage
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: 30f35852-3f7e-4c0c-9a88-e127b4f97211@1
      displayName: Download Build Artifact
      inputs:
        alias: current
        artifact: drop
    - task: AzureWebApp@1
      displayName: Deploy to Azure Web App
      inputs:
        azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
        appType: 'webApp'
        appName: '$(WEBAPP_NAME)'
        package: '$(Pipeline.Workspace)/drop/.next/standalone'
        deploymentMethod: 'zipDeploy'