import "@/app/globals.css";
import Footer from "@/app/[lang]/components/footer";
import Navbar from "@/app/[lang]/components/navbar";
import { i18n } from '@/app/i18n.config';
import "@/app/globals.css";
import { Raleway } from 'next/font/google';

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '700'], // puedes ajustar los pesos según lo que necesites
  variable: '--font-raleway', // opcional, si quieres usarlo como una variable CSS
});


export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata = {
  title: "CAF",
  // description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const lang = params?.lang || i18n.defaultLocale;
  console.log(lang)
  return (
    <html lang={lang}>
      <body
        className={`${raleway.className} antialiased min-h-screen flex flex-col justify-between bg-white`}
      >
        <Navbar lang={lang} />
        <div className="flex-grow">
           {children}
        </div>
       
        <Footer lang={lang} />
      </body>
    </html>
  );
}
