name: Deploy Next.js SSR App to Azure Web App

on:
  push:
    branches:
      - main  # Cambiá si tu rama principal tiene otro nombre

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Instalar dependencias
        run: npm install

      - name: Build de la app Next.js
        run: npm run build

      - name: Preparar contenido standalone para despliegue
        run: |
          mkdir -p deploy/.next/static
          cp -r .next/standalone/* deploy/
          if [ -d ".next/static" ]; then cp -r .next/static/* deploy/.next/static/; fi
          if [ -d "public" ]; then cp -r public deploy/public; fi
          cp package.json deploy/

      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'caf-visualizador-red'  # Cambiá por el nombre real de tu app en Azure
          slot-name: 'production'
          package: ./deploy
