# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Next.js SSR App to Azure Web App

on:
  push:
    branches:
      - main  # o la rama que uses para producción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Instalar dependencias
        run: npm install

      - name: Build de la app Next.js
        run: npm run build

      - name: Preparar contenido standalone para despliegue
        run: |
          mkdir deploy
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/static
          cp -r public deploy/public || true
          cp package.json deploy/

      - name: Deploy a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'caf-visualizador-red'  # reemplazar con tu App Service name exacto
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./deploy
